services:
    backend:
        image: ghcr.io/maarifa-c/backen_image.github.io:latest
        ports:
            - 3000:3000
        environment:
            NODE_ENV: production
        restart: always
    